language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- pypy
install: python setup.py install
script: python setup.py test
deploy:
  provider: pypi
  user: glow-mdsol
  password:
    secure: g2xjQ5VKEJebSW4uhABZ6YbdiK/hmroZblt0pIQL+7l+DjBZVqnRqr1wWWufTbxXLccvkcAFZuCVll/sLHzjbCmQ6khYl2hA5ghAAtMc3IQ8vwX9dSNjZaFN9NWIdCr99BaRN0Tt8SIr70Vb9DjxSYLKIcia8TXBiiG55M79QDM=
  on:
    branch: master
  distributions: sdist bdist_wheel